unguarded fs.watchFile cache statWatchers checking fixed
fs.watchFile code had checks for cached previously seen filepaths where the
check was not adequately protected against property name collisions:

      if (statWatchers[filename]) {

could have false positives if the filepath was a chained Object property
name, e.g. 'hasOwnProperty'.  Wild-looking errors would ensue:

  TypeError: Object function hasOwnProperty() { [native code] } has no method 'ad
          at Object.watchFile (fs.js:646:8)
          at /node.js/node-1_fs/test/simple/test-fs-watch-file.js:101:8

Fix is to use hasOwnProperty in both places cache checks are done:

  function inStatWatchers(filename) {
    return Object.prototype.hasOwnProperty.call(statWatchers, filename);
  }

    if (inStatWatchers(filename)) {

Changes updates lib/fs.js and test/simple/test-fs-watch-file.js

Changes since review of previous commit

A more conventional implementation of the hasOwnProperty check.

Removed extra console.logs